language: go

go:
  - 1.15
  - 1.16

before_install:
  if [[ $TRAVIS_GO_VERSION == 1.7* ]]; then make deps; fi

script:
  - if [[ $TRAVIS_GO_VERSION == 1.7* ]]; then make linters; fi
  - make test
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
