language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - sudo pip install codecov
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -race -cpu=1,2,4 -coverprofile=coverage.txt -covermode=count

after_success:
  - codecov
